### ISSUE TITLE
Remove sass

### ISSUE THREAD

**Issue by samhstn** [samhstn/samhstn#2]
This is overkill.

There should be no css pre-processing.

Maintaining this is going to be hard enough without the adding another package - adding dependencies should be avoided at all costs.

**Comment by nelsonic** [comment]
@Samhstn we’re you *recently* “burned” by a bad dependency...? 😕
(Or are you just streamilinging to de clutter?)

**Comment by samhstn** [comment]
I have been thinking about tech debt and clean code and came to this conclusion (this will be propagating through all my projects) - I am also now heeding the wisdom of more experienced software engineers 😉

**Comment by nelsonic** [comment]
Dependencies = Tech Debt ... Truth. 
https://github.com/dwyl/technical-glossary/issues/10
