### ISSUE TITLE
Configure iam user group which can only access samhstn resources

### ISSUE THREAD

**Issue by samhstn** [samhstn/samhstn#73]
Currently the aws console is being cluttered by different resources from different projects.

It would be really nice if we created an `Admin` type user who can view, create, update or delete resources which are related to the `samhstn` project - and only the `samhstn` project.

That way we can have a cleaner view of exactly what we are working on at any time and not accidentally change anything not related to what we are working on.

These permissions should be set referencing aws tagged resources - where these users should only see resources tagged with `samhstn` and should always include the `samhstn` tag when interacting with any resources.

This should affect both the Management console access user as well as the programmatic access user.

**Comment by samhstn** [comment]
I have had a lot of difficulty configuring these iam policies via some sort of tagging and grouping system. From here (https://aws.amazon.com/premiumsupport/knowledge-center/restrict-ec2-iam), it seems as though a lot of what I'm trying to do isn't possible.

From reading [this article](https://winterwindsoftware.com/managing-separate-projects-in-aws/), it seems that out of his suggested approaches, the current project naming convention might be the best way to go.

After some further reading, I stumbled across AWS organisations. This is **exactly** what I'm looking for and very easy to set up.

**Comment by nelsonic** [comment]
@samhstn AWS organisations good plan. 👍
