### ISSUE TITLE
Elixir formatter

### ISSUE THREAD

**Issue by samhstn** [samhstn/samhstn#92]
- [ ] Add `mix format` task to `buildspec`.
- [ ] Ensure all `ex` and `exs` files are formatted.

**Comment by nelsonic** [comment]
@samhstn should this be done using a `pre-commit` hook e.g: https://github.com/dwyl/elixir-pre-commit
so that code is formatted _before_ it gets to Version Contol / CI? ✨ 
Then you can run a _check_ for formatting in the `pre_build` 👍 / 👎  ? 💭

**Comment by samhstn** [comment]
Opting for a non elixir specific pre-commit hook solution. As I'm soon going to run more than `mix` tasks in pre-commit.
Would have used if it was more of a pure elixir project.

**Comment by nelsonic** [comment]
@samhstn if you find a good solution for multi-language pre-commit hook please share! 👍
